name: "posts_app"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sync:
    image: docker.io/electricsql/electric:latest
    environment:
      # Use the service name 'db' as the hostname
      DATABASE_URL: postgresql://user:password@db:5432/db?sslmode=disable
      ELECTRIC_INSECURE: true
    ports:
      - "3000:3000" # Default ElectricSQL pg-proxy port is 65432, but often mapped differently
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
